force-app/main/default/objects/CanvasCourse__c/CanvasCourse__c.object-meta.xml
<CustomObject>
    <label>Canvas Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canvas Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasCourse__c/fields/BlueprintCanvasCourseId__c.field-meta.xml
<CustomField>
    <fullName>BlueprintCanvasCourseId__c</fullName>
    <label>Blueprint Canvas Course ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/CanvasCourseId__c.field-meta.xml
<CustomField>
    <fullName>CanvasCourseId__c</fullName>
    <externalId>true</externalId>
    <label>Canvas Course ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/CanvasSubAccountId__c.field-meta.xml
<CustomField>
    <fullName>CanvasSubAccountId__c</fullName>
    <defaultValue>$Setup.Canvas_Settings__c.sub_account_id__c</defaultValue>
    <externalId>true</externalId>
    <inlineHelpText>When creating a new course, defaults to the account defined in Custom Settings/Canvas API Settings, but another account id may be entered (subject to accounts available to the Canvas token being used).</inlineHelpText>
    <label>Canvas Sub Account ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Site Available Until</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Site Available From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/triggers/syncCourseToCanvasTriggerTestClass.cls
@isTest
private class syncCourseToCanvasTriggerTestClass {
   static testMethod void myUnitTest() {
      //Create Data for Customer Objet
      CanvasCourse__c  canvasObj = new CanvasCourse__c();
      canvasObj.CanvasCourseId__c = 123;
      canvasObj.CanvasSubAccountId__c = 10;
      canvasObj.Title__c = 'Test Title';
      insert canvasObj;
      
      // Now, our trigger will fire on After update event so update the Records
      // Test.startTest();    // Starts the scope of test
      // //Set mock callout class
      // Test.setMock(HttpCalloutMock.class, new SingleRequestMock());
      // canvasObj.Title__c = 'New Title';
      // update canvasObj;
      // Test.stopTest();     // Ends the scope of test
      
      // Now check if it is giving desired results using system.assert
      CanvasCourse__c c = [SELECT Id, Name, Title__c, CanvasCourseId__c, Start_Date__c,
       End_Date__c, CanvasSubAccountId__c, BlueprintCanvasCourseId__c
        FROM CanvasCourse__c WHERE CanvasCourseId__c = :canvasObj.CanvasCourseId__c LIMIT 1];        
        
      system.assertEquals(c.Title__c,'New Title');
   }
}