force-app/main/default/objects/Canvas_Settings__c/Canvas_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Canvas settings for callouts to the API</description>
    <label>Canvas API Settings</label>
</CustomObject>

force-app/main/default/objects/Canvas_Settings__c/fields/ApiGatewayBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>ApiGatewayBaseUrl__c</fullName>
    <label>API Gateway Base URL</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Canvas_Settings__c/fields/ApiGatewayKey__c.field-meta.xml
<CustomField>
    <fullName>ApiGatewayKey__c</fullName>
    <label>API Gateway Key</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Canvas_Settings__c/fields/base_url__c.field-meta.xml
<CustomField>
    <fullName>base_url__c</fullName>
    <label>Base URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Canvas_Settings__c/fields/sub_account_id__c.field-meta.xml
<CustomField>
    <fullName>sub_account_id__c</fullName>
    <defaultValue></defaultValue>
    <externalId>true</externalId>
    <label>Sub-account ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Canvas_Settings__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <description>Canvas API token</description>
    <label>token</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/CanvasCourse__c.object-meta.xml
<CustomObject>
    <label>Canvas Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canvas Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasCourse__c/fields/CanvasCourseId__c.field-meta.xml
<CustomField>
    <fullName>CanvasCourseId__c</fullName>
    <externalId>true</externalId>
    <label>Canvas Course ID</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/CanvasSubAccountId__c.field-meta.xml
<CustomField>
    <fullName>CanvasSubAccountId__c</fullName>
    <defaultValue>$Setup.Canvas_Settings__c.sub_account_id__c</defaultValue>
    <externalId>true</externalId>
    <inlineHelpText>When creating a new course, defaults to the account defined in Custom Settings/Canvas API Settings, but another account id may be entered (subject to accounts available to the Canvas token being used).</inlineHelpText>
    <label>Canvas Sub Account ID</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Default Term</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>2017</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>2017 Interval 1</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>2017 Interval 2</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>2017 Interval 3</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>2017 Interval 4</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>2017 Interval 5</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>2017 Interval 6</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>2017 Interval 7</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>2017 Interval 8</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>2017 Interval 9</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>2017 Interval 10</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>2017 Interval 11</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>2017 Interval 12</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>2018</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>2018 Interval 1</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>2018 Interval 2</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>2018 Interval 3</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>2018 Interval 4</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>2018 Interval 5</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>2018 Interval 6</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>2018 Interval 7</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>2018 Interval 8</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>2018 Interval 9</label>
            </value>
            <value>
                <fullName>25</fullName>
                <label>2018 Interval 10</label>
            </value>
            <value>
                <fullName>26</fullName>
                <label>2018 Interval 11</label>
            </value>
            <value>
                <fullName>27</fullName>
                <label>2018 Interval 12</label>
            </value>
            <value>
                <fullName>28</fullName>
                <label>2019</label>
            </value>
            <value>
                <fullName>29</fullName>
                <label>2019 Interval 1</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>2019 Interval 2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CanvasEnrollment__c/CanvasEnrollment__c.object-meta.xml
<CustomObject>
    <description>Represents the enrollment of a contact in a course</description>
    <label>Canvas Enrollment</label>
    <nameField>
        <displayFormat>ENRL-{0000}</displayFormat>
        <label>Canvas Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasEnrollment__c/fields/CanvasCourse__c.field-meta.xml
<CustomField>
    <fullName>CanvasCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canvas Course</label>
    <referenceTo>CanvasCourse__c</referenceTo>
    <relationshipLabel>Canvas Enrollments</relationshipLabel>
    <relationshipName>CanvasEnrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CanvasEnrollment__c/fields/CanvasEnrollmentId__c.field-meta.xml
<CustomField>
    <fullName>CanvasEnrollmentId__c</fullName>
    <externalId>true</externalId>
    <label>Canvas Enrollment ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CanvasEnrollment__c/fields/CanvasUser__c.field-meta.xml
<CustomField>
    <fullName>CanvasUser__c</fullName>
    <label>Canvas User</label>
    <referenceTo>CanvasUser__c</referenceTo>
    <relationshipLabel>Canvas Enrollments</relationshipLabel>
    <relationshipName>CanvasEnrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CanvasEnrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Concluded</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CanvasUser__c/CanvasUser__c.object-meta.xml
<CustomObject>
    <label>Canvas User</label>
    <nameField>
        <displayFormat>CNV-USR-{0000}</displayFormat>
        <label>Canvas User Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasUser__c/fields/CanvasUserId__c.field-meta.xml
<CustomField>
    <fullName>CanvasUserId__c</fullName>
    <externalId>true</externalId>
    <label>Canvas User ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CanvasUser__c/fields/ConfirmationUrl__c.field-meta.xml
<CustomField>
    <fullName>ConfirmationUrl__c</fullName>
    <description>The URL that takes the user through the account confirmation process (so they can set up a password).</description>
    <label>Confirmation URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CanvasUser__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CanvasUser__c/fields/Fullname__c.field-meta.xml
<CustomField>
    <fullName>Fullname__c</fullName>
    <label>Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/CanvasClientTestSuite.cls
@isTest
private class CanvasClientTestSuite {

    static testMethod void testSyncCanvasCourse() {
        Test.startTest();    // Starts the scope of test

        Canvas_Settings__c settings = new Canvas_Settings__c(ApiGatewayBaseUrl__c = 'api_gateway_base_url',
                                                             ApiGatewayKey__c = 'gateway_key', 
                                                             base_url__c = 'base_url', 
                                                             sub_account_id__c = 5, 
                                                             token__c = 'test_token');
        insert settings;
        
        CanvasCourse__c  canvasCourse = new CanvasCourse__c(CanvasCourseId__c = 123,
                                                            CanvasSubAccountId__c = 10,
                                                            Term__c = '1',
                                                            Title__c = 'Test Title');        // insert canvasCourse;        

        CanvasUser__c canvasUser = new CanvasUser__c(CanvasUserId__c = 1234,
                                                     ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                     Email__c = 'test@email.com',
                                                     Fullname__c = 'Joe Johnson');

        CanvasUser__c canvasUserNoId = new CanvasUser__c(CanvasUserId__c = 1234,
                                                         ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                         Email__c = 'test@email.com',
                                                         Fullname__c = 'Joe Johnson');

        String testCourseJson = '{"id":6623,"name":"Test Course","account_id":749,"uuid":"Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU","start_at":null,"conclude_at":null,"grading_standard_id":null,"is_public":null,"allow_student_forum_attachments":false,"course_code":"TestCourseCode","default_view":"modules","root_account_id":1,"enrollment_term_id":1,"open_enrollment":null,"allow_wiki_comments":null,"self_enrollment":null,"license":null,"restrict_enrollments_to_course_dates":false,"end_at":null,"public_syllabus":false,"public_syllabus_to_auth":false,"storage_quota_mb":1000,"is_public_to_auth_users":false,"hide_final_grades":false,"apply_assignment_group_weights":false,"calendar":{"ics":"https://canvas.dev.tlt.harvard.edu/feeds/calendars/course_Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU.ics"},"time_zone":"America/New_York","blueprint":false,"sis_course_id":"a013D000004J5xkQAC","sis_import_id":null,"integration_id":null,"workflow_state":"unpublished"}';
        String testUserJson = '{"id":12345,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Aikaterini-Pavlina Tsoka","sis_user_id":"10930448","integration_id":null,"sis_import_id":36425,"login_id":"10930448"},{"id":154483,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Christopher Thornton","sis_user_id":"913","integration_id":null,"sis_import_id":49189,"login_id":"913"}';

        SingleRequestMock courseDoesntExistResp = new SingleRequestMock(200, 'Complete', testCourseJson, null);
        Test.setMock(HttpCalloutMock.class, courseDoesntExistResp);
        insert canvasCourse;

        SingleRequestMock courseDoesExistResp = new SingleRequestMock(404, 'Complete', testCourseJson, null);
        Test.setMock(HttpCalloutMock.class, courseDoesExistResp);
        CanvasClient.syncCanvasCourse(canvasCourse.Id);

        Test.stopTest();

    } // testSyncCanvasCourse()

    static testMethod void testSyncCanvasUser() {
        Test.startTest();    // Starts the scope of test

        Canvas_Settings__c settings = new Canvas_Settings__c(ApiGatewayBaseUrl__c = 'api_gateway_base_url',
                                                             ApiGatewayKey__c = 'gateway_key', 
                                                             base_url__c = 'base_url', 
                                                             sub_account_id__c = 5, 
                                                             token__c = 'test_token');
        insert settings;
        
        CanvasCourse__c  canvasCourse = new CanvasCourse__c(CanvasCourseId__c = 123,
                                                            CanvasSubAccountId__c = 10,
                                                            Title__c = 'Test Title');        // insert canvasCourse;        

        CanvasUser__c canvasUser = new CanvasUser__c(CanvasUserId__c = 1234,
                                                     ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                     Email__c = 'test@email.com',
                                                     Fullname__c = 'Joe Johnson');

        CanvasUser__c canvasUserNoId = new CanvasUser__c(CanvasUserId__c = 1234,
                                                         ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                         Email__c = 'test@email.com',
                                                         Fullname__c = 'Joe Johnson');

        String testCourseJson = '{"id":6623,"name":"Test Course","account_id":749,"uuid":"Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU","start_at":null,"conclude_at":null,"grading_standard_id":null,"is_public":null,"allow_student_forum_attachments":false,"course_code":"TestCourseCode","default_view":"modules","root_account_id":1,"enrollment_term_id":1,"open_enrollment":null,"allow_wiki_comments":null,"self_enrollment":null,"license":null,"restrict_enrollments_to_course_dates":false,"end_at":null,"public_syllabus":false,"public_syllabus_to_auth":false,"storage_quota_mb":1000,"is_public_to_auth_users":false,"hide_final_grades":false,"apply_assignment_group_weights":false,"calendar":{"ics":"https://canvas.dev.tlt.harvard.edu/feeds/calendars/course_Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU.ics"},"time_zone":"America/New_York","blueprint":false,"sis_course_id":"a013D000004J5xkQAC","sis_import_id":null,"integration_id":null,"workflow_state":"unpublished"}';
        String testUserJson = '[{"id":12345,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Aikaterini-Pavlina Tsoka","sis_user_id":"10930448","integration_id":null,"sis_import_id":36425,"login_id":"10930448"},{"id":154483,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Christopher Thornton","sis_user_id":"913","integration_id":null,"sis_import_id":49189,"login_id":"913"}]';
        
        SingleRequestMock userExistsResp = new SingleRequestMock(200, 'Complete', testUserJson, null);
        Test.setMock(HttpCalloutMock.class, userExistsResp);
        insert canvasUser;

        canvasUser.CanvasUserId__c = null;
        update canvasUser;
        // CanvasClient.syncCanvasUser(canvasUser.id);
        
        Test.stopTest();
    }

    static testMethod void testSyncEnrollmentToCanvas() {
        Test.startTest();    // Starts the scope of test

        Canvas_Settings__c settings = new Canvas_Settings__c(ApiGatewayBaseUrl__c = 'api_gateway_base_url',
                                                             ApiGatewayKey__c = 'gateway_key', 
                                                             base_url__c = 'base_url', 
                                                             sub_account_id__c = 5, 
                                                             token__c = 'test_token');
        insert settings;
        
        CanvasCourse__c  canvasCourse = new CanvasCourse__c(CanvasCourseId__c = 123,
                                                            CanvasSubAccountId__c = 10,
                                                            Title__c = 'Test Title');        // insert canvasCourse;        

        CanvasUser__c canvasUser = new CanvasUser__c(CanvasUserId__c = 1234,
                                                     ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                     Email__c = 'test@email.com',
                                                     Fullname__c = 'Joe Johnson');

        CanvasUser__c canvasUserNoId = new CanvasUser__c(CanvasUserId__c = 1234,
                                                         ConfirmationUrl__c = 'https://canvas.dev.harvard.edu',
                                                         Email__c = 'test@email.com',
                                                         Fullname__c = 'Joe Johnson');

        String testCourseJson = '{"id":6623,"name":"Test Course","account_id":749,"uuid":"Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU","start_at":null,"conclude_at":null,"grading_standard_id":null,"is_public":null,"allow_student_forum_attachments":false,"course_code":"TestCourseCode","default_view":"modules","root_account_id":1,"enrollment_term_id":1,"open_enrollment":null,"allow_wiki_comments":null,"self_enrollment":null,"license":null,"restrict_enrollments_to_course_dates":false,"end_at":null,"public_syllabus":false,"public_syllabus_to_auth":false,"storage_quota_mb":1000,"is_public_to_auth_users":false,"hide_final_grades":false,"apply_assignment_group_weights":false,"calendar":{"ics":"https://canvas.dev.tlt.harvard.edu/feeds/calendars/course_Fy0Sx97QMJGQ0yKZdYqx7xJ9yH1bY2Qv9GG33pxU.ics"},"time_zone":"America/New_York","blueprint":false,"sis_course_id":"a013D000004J5xkQAC","sis_import_id":null,"integration_id":null,"workflow_state":"unpublished"}';
        String testUserJson = '{"id":12345,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Aikaterini-Pavlina Tsoka","sis_user_id":"10930448","integration_id":null,"sis_import_id":36425,"login_id":"10930448"},{"id":154483,"name":"Christopher Thornton","sortable_name":"Thornton, Christopher","short_name":"Christopher Thornton","sis_user_id":"913","integration_id":null,"sis_import_id":49189,"login_id":"913"}';
        
        SingleRequestMock courseExistsResp = new SingleRequestMock(200, 'Complete', testCourseJson, null);
        Test.setMock(HttpCalloutMock.class, courseExistsResp);

        insert canvasUser;
        insert canvasCourse;

        CanvasEnrollment__c canvasEnrollment = new CanvasEnrollment__c(CanvasCourse__c = canvasCourse.Id,
                                                                       CanvasEnrollmentId__c = 12345,
                                                                       CanvasUser__c = canvasUser.Id,
                                                                       Status__C = 'Active');

        insert canvasEnrollment;
        // CanvasClient.syncEnrollmentToCanvas(canvasEnrollment.Id, 'delete');

        CanvasClient.subscribeToBlueprintCourse(canvasCourse.Id, 123,123);

        // Putting in calls to methods to get some additional coverage
        CanvasClient.userToJson(canvasUser);
        
        Test.stopTest();
    }

    // TODO Implement unit tests for the following methods
    // public static void syncCanvasCourse(Id canvasCourseRecordId)
    // public static void syncCanvasUser(Id canvasUserRecordId)
    // public static void syncEnrollmentToCanvas(Id canvasEnrollmentId, String requestType)
    // private static void  subscribeToBlueprintCourse(Decimal BlueprintCanvasCourseId, Decimal currentCanvasCourseId)
    // private static String courseToJson(CanvasCourse__c canvasCourse)
    // private static CanvasCourse__c jsonToCourse(String jsonCourse, CanvasCourse__c canvasCourse)
    // private static String userToJson(CanvasUser__c canvasUser)
    // private static String userToJsonForUpdate(CanvasUser__c canvasUser)
    // private static CanvasUser__c jsonToUser(String jsonUser, CanvasUser__c canvasUser)
    // private static String enrollmentToJson(CanvasEnrollment__c canvasEnrollment)
    // private static CanvasEnrollment__c jsonToEnrollment(String jsonEnrollment, CanvasEnrollment__c canvasEnrollment)


    static testMethod void testPrepareRequest(){
        // TODO Have settings as a global setup
        Canvas_Settings__c settings = new Canvas_Settings__c(ApiGatewayBaseUrl__c = 'api_gateway_base_url',
                                                             ApiGatewayKey__c = 'gateway_key', 
                                                             base_url__c = 'base_url', 
                                                             sub_account_id__c = 5, 
                                                             token__c = 'test_token');

        HttpRequest reqUseGateway = CanvasClient.prepareRequest('test/path/', 'POST', settings, true);
        System.assertEquals('POST', reqUseGateway.getMethod());
        System.assertEquals('api_gateway_base_url'+'api/v1/'+'test/path/', reqUseGateway.getEndpoint());
        System.assertEquals('gateway_key', reqUseGateway.getHeader('x-api-key'));

        HttpRequest reqNoGateway = CanvasClient.prepareRequest('test/path/', 'POST', settings, false);
        System.assertEquals('base_url'+'api/v1/'+'test/path/', reqNoGateway.getEndpoint());
        System.assertEquals('Bearer '+'test_token', reqNoGateway.getHeader('Authorization'));
    } // testPrepareRequest()

} // class CanvasClientTestSuite