force-app/main/default/objects/Canvas_Settings__c/Canvas_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Canvas settings for callouts to the API</description>
    <label>Canvas API Settings</label>
</CustomObject>

force-app/main/default/objects/Canvas_Settings__c/fields/base_url__c.field-meta.xml
<CustomField>
    <fullName>base_url__c</fullName>
    <label>Base URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/MockHttpResponseGenerator.cls
@isTest
global class MockHttpResponseGenerator implements HttpCalloutMock {

    // Implement this interface method

    global HTTPResponse respond(HTTPRequest req) {

        // Optionally, only send a mock response for a specific endpoint

        // and method.
        Canvas_Settings__c settings = new Canvas_Settings__c();
        settings.base_url__c = 'canvas_url';

        // currently hardcoding the null as it's not clear how to pass the base url
        System.assertEquals('nullapi/v1/courses/123', req.getEndpoint());

        System.assertEquals('GET', req.getMethod());
        
         

        // Create a fake response

        HttpResponse res = new HttpResponse();

        res.setHeader('Content-Type', 'application/json');

        res.setBody('{"example":"test"}');

        res.setStatusCode(201);

        return res;

    }

}