force-app/main/default/objects/CanvasActivityLog__c/fields/CanvasCourse__c.field-meta.xml
<CustomField>
    <fullName>CanvasCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canvas Course</label>
    <referenceTo>CanvasCourse__c</referenceTo>
    <relationshipName>Canvas_Sync_Activity_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CanvasActivityLog__c/fields/CanvasEnrollment__c.field-meta.xml
<CustomField>
    <fullName>CanvasEnrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canvas Enrollment</label>
    <referenceTo>CanvasEnrollment__c</referenceTo>
    <relationshipName>Canvas_Sync_Activity_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CanvasCourse__c/CanvasCourse__c.object-meta.xml
<CustomObject>
    <label>Canvas Course</label>
    <nameField>
        <label>Course Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canvas Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasEnrollment__c/CanvasEnrollment__c.object-meta.xml
<CustomObject>
    <description>Represents the enrollment of a contact in a course</description>
    <label>Canvas Enrollment</label>
    <nameField>
        <displayFormat>ENRL-{0000}</displayFormat>
        <label>Canvas Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CanvasEnrollment__c/fields/CanvasCourse__c.field-meta.xml
<CustomField>
    <fullName>CanvasCourse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canvas Course</label>
    <referenceTo>CanvasCourse__c</referenceTo>
    <relationshipLabel>Canvas Enrollments</relationshipLabel>
    <relationshipName>CanvasEnrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CanvasEnrollment__c/fields/CanvasUser__c.field-meta.xml
<CustomField>
    <fullName>CanvasUser__c</fullName>
    <label>Canvas User</label>
    <referenceTo>CanvasUser__c</referenceTo>
    <relationshipLabel>Canvas Enrollments</relationshipLabel>
    <relationshipName>CanvasEnrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CanvasUser__c/CanvasUser__c.object-meta.xml
<CustomObject>
    <label>Canvas User</label>
    <nameField>
        <displayFormat>CNV-USR-{0000}</displayFormat>
        <label>Canvas User Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canvas Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/CanvasHelper.cls
public with sharing class CanvasHelper {

    public static void ActivityLogGenerate(String level, String message, String source, Id courseId, Id enrollmentId, Id userId) {
        CanvasActivityLog__c log = new  CanvasActivityLog__c();
        log.LEVEL__c = level;                          
        log.Message__c = message;
        log.Source__c = source;
        log.CanvasCourse__c = courseId;
        log.CanvasEnrollment__c = enrollmentId;
        log.CanvasUser__c = userId;
        insert log; 
    }
}